### ISSUE TITLE
Fency-1.0.0-1.18.2-1 causes server crash

### ISSUE THREAD

**Issue by rckymtnrfc** [TheMrMilchmann/TheFenceUnleashed#1]
Looks like this is the issue - Attempted to load class net/minecraft/client/player/LocalPlayer for invalid dist DEDICATED_SERVER)

Forge 40.1.0
Fency 1.0.0-1.18.2-1

Full server Log - https://pastebin.com/ckAuknKW

**Comment by TheMrMilchmann** [comment]
Thanks for reporting. This will be fixed in `1.0.0-1.18.2-2` which is currently awaiting approval from CurseForge and should be available soon.

In case it's urgent, the JAR in this archive contains is identical to the CF release: [Fency-1.0.0-1.18.2-2.zip](https://github.com/TheMrMilchmann/TheFenceUnleashed/files/8597391/Fency-1.0.0-1.18.2-2.zip)
