### ISSUE TITLE
alexs mobs monkeys go through gates

### ISSUE THREAD

**Issue by Jadan1213** [TheMrMilchmann/TheFenceUnleashed#13]
### Description

The monkeys run through the gates. I've tried to add the mob id in various forms to the blacklist to prevent it, but i can not keep them contained.

### Mod version

1.0.2

### Forge version

47.2.17

**Comment by TheMrMilchmann** [comment]
Hi @Jadan1213, after doing a bit of testing, I assume you are talking about Capuchin monkeys specifically. These jump over fences and fence gates (instead of passing through the gates).

https://github.com/TheMrMilchmann/TheFenceUnleashed/assets/4029915/62cfc6b0-cc4b-41a9-9a8e-98db9392117d

The Fence Unleashed only affects entities that are passing through fence gates. There is no reasonable way to prevent stuff from jumping over fences. So, this is not a bug in this mod.

**Comment by Jadan1213** [comment]
I totally understand what you mean. However to combat this, i built a complete enclosure with a double gate system to keep them contained. I wasn't sure if this was something doable with the mod or not. I'll just stick to a fully enclosed "cage". Thank you so much for taking the time to test it out!

**Comment by Jadan1213** [comment]
it looks like if i do two vertical gates, it keeps them contained.
![image](https://github.com/TheMrMilchmann/TheFenceUnleashed/assets/68805162/10aa1f58-9bba-499e-b116-f98a4c69c5d1)

**Comment by Jadan1213** [comment]
Thank you again, sorry to have wasted your time!
