### ISSUE TITLE
MineColonies citizens cannot pass fence gates

### ISSUE THREAD

**Issue by Agentx49** [TheMrMilchmann/TheFenceUnleashed#2]
Could you please add an exception for minecolonies npcs

**Comment by TheMrMilchmann** [comment]
Hi, the mod has a config which can be used to adjust its behaviour and add exceptions. For your particular issue, you would want to add the ID of the MineColonies citizens to the allowlist.

I'd give you an example but since I'm currently on vacation, I don't have any at hand. (cc @Zdesl)

**Comment by Zdesl** [comment]
It should work if you edit allowlist in the "the-fence-unleashed.toml" config file like this.
`allowlist = ["minecolonies:citizen"]`

**Comment by Agentx49** [comment]
Thank you I will try this when I get home

**Comment by TheMrMilchmann** [comment]
Closing, as a functioning workaround has been provided.

**Comment by Agentx49** [comment]
sorry just saw this, and yes the config change did work for me

**Comment by rckymtnrfc** [comment]
You may want to add minecolonies:vistor as well to the config.  Otherwise, the new towns-people that spawn can get stuck not being able to access buildings like the tavern.

**Comment by TheMrMilchmann** [comment]
Thanks, @rckymtnrfc for letting me know! In a future update, I'll probably add `minecolonies:visitor` to the default config. Technically, this is still just a workaround though because raiders (and potentially other stuff) would have to be added too. I have to check if this can be reasonably tweaked on MineColonies end to make the inference work which should remove the need for the workaround altogether.
